spring:
  application:
    name: kentkartstatsapi
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://${DB_HOST}:5432/${DB_NAME}?allowPublicKeyRetrieval=true&useUnicode=yes&characterEncoding=UTF8&verifyServerCertificate=false&useSSL=false&requireSSL=false
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver

jwt:
  token:
    expiration: 1800000
    secret-key: "kadircokgizlisifre777"